### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by itsmedhaaz** [azkal182/lk21unofficial#1]
Gak bisa play video nya bang, fix dong bang

**Comment by azkal182** [comment]
Harus pake extensi chrome https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino, kalo mau pake android harus pake kiwi browser dan install ektensi itu, aku belum sempat benerin

**Comment by azkal182** [comment]
Coba lg bro, tpi ndak saya lanjutin dulu projek nya, ndak ada waktu
